### ISSUE TITLE
Question: Fit3D synchronization of frames and joint data

### ISSUE THREAD

**Issue by ChristianIngwersen** [sminchisescu-research/imar_vision_datasets_tools#1]
Hi,

Thanks for your great contributing with the datasets and code. 
I'm struggeling to figure out how to precicely match the extracted frames with the joint data for the Fit3D dataset.

When using the `read_data()` function there should according to you notebook `visualize_lab_dataset.ipynb`be a `"fr_id"` key in the annotations for the chi3d dataset. 
I can't seem to find this information for the Fit3D data. I guess i could do a rough matching be knowing the video is recorded at 50fps while the marker data is recorded at 200 fps, but is there anyway to do a more precise matching?

**Comment by mihaifieraru** [comment]
Hi Christian,

CHI3D annotations have a 'fr_id' key, as that holds one annotated frame id where the 2 people are in contact. Same for HumanSC3D, where the 'fr_id' is annotated as a timestamp where there's for sure self-contact. In the case of Fit3D, we did not annotate any fr_id of interest. 

Also, you are right about frame rates. We always to matching as follows:
j3d_fr_id = 4 * rgb_fr_id = 4 * ghum_fr_id = 4 * smplx_fr_id

**Comment by ChristianIngwersen** [comment]
Good to know!
I guess this could be improved by using the timestamp metadata depending on your Vicon system? 
When e.g. doing a burpee this potential marker/frame offset might be visible in the jumping phase?

**Comment by mihaifieraru** [comment]
So far, we have not noticed any significant offset, not even in high speed motions. Please let us know if you find any significant offsets.  Thanks!

**Comment by ChristianIngwersen** [comment]
Thanks, will do!
