### ISSUE TITLE
Testing on images from different dataset

### ISSUE THREAD

**Issue by ocissor** [sminchisescu-research/imar_vision_datasets_tools#2]
Hi, I was going through your paper and found it very interesting and while I was going through the GitHub repo I could not find code to generate reconstructions for images from different datasets like I want to generate results for the TV-Human interaction dataset. Can you please guide me on how can I generate results for images from different datasets?
Thank you.

**Comment by mihaifieraru** [comment]
Hi! This repo does not contain code for reconstructing people in new images. For AIFit, we reconstruct in-the-wild images with https://github.com/alinionutpopa/MubyNet. The optimization code for the contact papers (ci3d.imar.ro and sc3d.imar.ro) is unfortunately not released.
