### ISSUE TITLE
Test Data for AIFit3D are missing.

### ISSUE THREAD

**Issue by VoidLLY** [sminchisescu-research/imar_vision_datasets_tools#4]
Hi, thank you so much for presenting this great work. When I was trying to download test data from AIFit3D dataset for research purpose, I notice the 3D joints groundtruth data and pose parameters in test dataset are missing. Will you release these data later? Thank you.

**Comment by mihaifieraru** [comment]
Hi! The test set ground truth data will not be publicly available, as it is used to evaluate predictions in the current available benchmark. If you submit your 3d pose estimation predictions on the website, the evaluation server will compute and show you most of the relevant evaluation metrics.

**Comment by VoidLLY** [comment]
> Hi! The test set ground truth data will not be publicly available, as it is used to evaluate predictions in the current available benchmark. If you submit your 3d pose estimation predictions on the website, the evaluation server will compute and show you most of the relevant evaluation metrics.

Ok. Got it. Thanks for the reply.
