### ISSUE TITLE
Questions about CHI3D

### ISSUE THREAD

**Issue by chenzhu01** [sminchisescu-research/imar_vision_datasets_tools#5]
Hello, thanks for your great contributing with the datasets. I noticed that the CHI3D training set only had annotations for one person. How do I get the smplx parameter and 3d-joints positions for the other one?

**Comment by mihaifieraru** [comment]
Hello! Annotations for both persons are available already. To visualize them, please use this notebook https://github.com/sminchisescu-research/imar_vision_datasets_tools/blob/main/notebooks/visualize_lab_dataset.ipynb and modify the last line in the third cell: 

subject = 'w_markers'

changes into

subject = 'wo_markers'

**Comment by chenzhu01** [comment]
Thanks for the reply, but I opened with notebook in the smplx json file only one person parameter. May I ask if it is because the dataset is updated? The data zip for my training set is only 3.5G in size.

![image](https://github.com/sminchisescu-research/imar_vision_datasets_tools/assets/101321457/590ef5be-58e2-42e2-83e6-5792fce88868)

**Comment by mihaifieraru** [comment]
Yes! We added the 2nd person and updated the dataset a couple of months ago. Please re-download.

**Comment by chenzhu01** [comment]
Thanks!
